config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy", as: :logout

  resources :pages
  resources :widgets
  resources :layouts
  resources :sites

  resources :changes, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset_list.rb
class AssetList < Widget
  # http://stackoverflow.com/questions/4507149/best-practices-to-handle-routes-for-sti-subclasses-in-rails
  def self.model_name
    Widget.model_name
  end
end

app/models/change.rb
class Change < ApplicationRecord
  belongs_to :user

  validates :controller, presence: true
  validates :action, presence: true
  validates :params, presence: true

  serialize :params, JSON
  serialize :model_attributes, JSON

  def to_s
    "#{controller}/#{action}"
  end
end

app/models/layout.rb
class Layout < ApplicationRecord
  has_many :pages

  def sections
    read_attribute(:sections).try(:map) { |s| s['key'] }
  end

  def sections=(sections)
    section_keys = sections.present? ? sections.split(/,|\s/).map(&:strip).reject(&:blank?) : []
    write_attribute(:sections, section_keys.map { |key| {key: key} })
  end
end

app/models/migrate_util.rb
module MigrateUtil
  def self.foreign_key(table, column, to_table, options = {})
    options[:to_column] ||= "id"
    options[:on_delete] ||= "cascade"
    "alter table #{table} add constraint #{table}_#{column}_fk foreign key (#{column}) " +
    "references #{to_table}(#{options[:to_column]}) on delete #{options[:on_delete]}"
  end
end

app/models/nullify_params.rb
module NullifyParams
  def self.nullify!(params)
    params.each do |key, value|
      if value.is_a?(String) && value.blank?
        params[key] = nil
      elsif value.is_a?(Hash) || value.is_a?(ActionController::Parameters)
        nullify!(value)
      end
    end
  end
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, presence: true
  validates :site_id, presence: true
  validates :path, presence: true

  belongs_to :site
  belongs_to :layout
  has_many :published_paths, as: :item
  Versioned.add(self, columns: [:title, :path, :body, :doc, :status, :publish_at, :unpublish_at])

  before_validation :set_default_status
  before_validation :set_default_path
  before_validation :set_normalized_path
  before_validation :check_path_unique
  after_save :save_published_path

  def published?
    status == 'published'
  end

  def widgets
    doc && doc['widgets']
  end

  def widgets=(widgets)
    if widgets.present?
      self.doc = {} if self.doc.blank? || self.doc == '{}'
      self.doc['widgets'] = widgets.reject(&:blank?).map(&:to_i)
    end
  end

  def set_default_status
    self.status ||= 'draft'
  end

  def set_default_path
    self.path ||= Path.default_path(title, site_id)
  end

  def set_normalized_path
    self.path = Path.normalize_path(path)
  end

  def check_path_unique
    if path && path_changed? && PublishedPath.exists?(path: path, site_id: site_id)
      self.errors.add(:path, "Already exists")
    end
  end

  def save_published_path
    if (path_changed? && published?) || (status_changed? && published?)
      published_paths.create!(path: path, site_id: site_id)
    end
  end
end

app/models/page_version.rb
class PageVersion < ApplicationRecord
end

app/models/path.rb
module Path
  def self.normalize_path(path)
    path.try(:parameterize)
  end

  def self.default_path(title, site_id, options = {})
    return nil if title.blank?
    suffix = options[:sequence] ? "-#{options[:sequence]}" : ''
    path = normalize_path(title) + suffix
    if PublishedPath.exists?(path: path, site_id: site_id)
      next_sequence = (options[:sequence] || 1) + 1
      default_path(title, site_id, sequence: next_sequence)
    else
      return path
    end
  end
end

app/models/published_path.rb
class PublishedPath < ApplicationRecord
  belongs_to :item, polymorphic: true
end

app/models/site.rb
class Site < ApplicationRecord
  validates :key, presence: true

  has_many :pages

  def to_s
    key
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: {with: /@/}

  has_many :change_history, class_name: 'Change'

  def to_s
    name
  end
end

app/models/versioned.rb
module Versioned
  def self.add(klass, options = {})
    klass.class_eval do
      cattr_accessor :version_class_name, :versioned_columns

      self.version_class_name = klass.to_s + "Version"
      self.versioned_columns = options[:columns]

      has_many :versions, class_name: version_class_name

      before_save :check_for_new_version

      private

      def check_for_new_version
        instantiate_version if create_new_version?
        true # Never halt save
      end

      def instantiate_version
        new_version = versions.build
        versioned_columns.each do |attribute|
          new_version.__send__ "#{attribute}=", __send__(attribute)
        end
        new_version.version_number = (new_record? ? 1 : versions.maximum(:version_number) + 1)
        self.version_number = new_version.version_number
      end

      def create_new_version?
        versioned_columns.detect {|a| __send__ "#{a}_changed?"}
      end
    end
  end
end

app/models/widget.rb
class Widget < ApplicationRecord
  def self.descendants
    # NOTE: does not work in development with lazy loaded classes
    # ObjectSpace.each_object(Class).select { |klass| klass < self }
    [AssetList]
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.order("id DESC")
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to widgets_path, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to widgets_path, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:type, :title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_ALERT_CLASSES = {
    notice: 'alert alert-success',
    alert: 'alert alert-danger',
    error: 'alert alert-danger',
    warning: 'alert alert-warning'
  }

  def bootstrap_alert_class(flash_name)
    BOOTSTRAP_ALERT_CLASSES[flash_name.to_sym]
  end
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<%= form_for(widget) do |f| %>
  <% if widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="form-group">
    <%= f.label :type %>
    <%= f.select :type, Widget.descendants.map {|c| [c, c] }, {}, {class: "form-control"} %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </fieldset>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Delete', @widget, method: :delete, data: { confirm: 'Are you sure?' } %>
| <%= link_to 'Cancel', widgets_path %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Widgets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Created at</th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= link_to widget.title, edit_widget_path(widget) %></td>
        <td><%= widget.type %></td>
        <td><%= widget.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path, class: "btn btn-primary" %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Cancel', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @widget.type %>
</p>

<p>
  <strong>Title:</strong>
  <%= @widget.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @widget.body %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>